#pragma once
#include "QScrollArea"
#include <QApplication>
#include <QtWidgets>
#include <antifirelogic_valves.h>
#include <antifirelogic_execution_block.h>
#include <antifirelogic_alarm.h>
#include <presure_regulation.h>
#include <antiicing_mkam.h>
#include <antiicing_airintake.h>
#include <antiicing_airintake_warmup.h>
#include <antiicing_ppd.h>
#include <antiicing_windshields.h>
#include <antiicing_lights.h>
#include <cabinlighting_navi.h>
#include <cabinlighting_beacons.h>
#include <cabinlighting_outside.h>
#include <cabinlighting_inner.h>
#include <cabinlighting_solid.h>
#include <emergencyalarm_steersman.h>
#include <emergencyalarm_leftpilot.h>
#include <emergencyalarm_leftpilot_1.h>
#include <emergencyalarm_leftpilot_2.h>
#include <emergencyalarm_rightpilot.h>
#include <emergencyalarm_rightpilot_1.h>
#include <emergencyalarm_navigator.h>
#include <emergencyalarm_navigator_1.h>
#include <emergencyalarm_navigator_2.h>
#include <landinggear_1.h>
#include <landinggear_2.h>
#include <landinggear_3.h>
#include <landinggear_4.h>
#include <landinggear_5.h>
#include <landinggear_6.h>
#include <landinggear_7.h>
#include <landinggear_8.h>
#include <landinggear_9.h>
#include <wingsmech_1.h>
#include <wingsmech_2.h>
#include <wingsmech_3.h>
#include <wingsmech_4.h>
#include <brakes_1.h>
#include <brakes_2.h>
#include <brakes_3.h>
#include <brakes_4.h>
#include <brakes_5.h>
#include <brakes_6.h>
#include <hydro_1.h>
#include <hydro_2.h>
#include <hydro_3.h>
#include <hydro_4.h>
#include <hydro_5.h>
#include <hydro_6.h>
#include <hydro_7.h>
#include <hydro_8.h>
#include <hydro_9.h>
#include "powerdc_int.h"
#include "hydro_int.h"
#include "brakes_int.h"
#include "wingsmech_int.h"
#include "landinggear_int.h"

